apiVersion: v1
kind: Service
metadata:
  name: green-service
spec:
  type: NodePort
  selector:
    app: my-app
    version: green
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080